[package]
name = "pwm"
version = "1.0.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
license = "Apache-2.0"

[dependencies]
bdrck_config = "0.2"
bdrck_log = "0.3"
bdrck_params = "0.3"
bincode = "0.8"
byteorder = "1.1"
clipboard = { version = "0.4", optional = true }
data-encoding = "2.0.0-rc.2"
error-chain = "0.11"
git2 = { version = "0.6", default-features = false, features = [] }
isatty = "0.1"
lazy_static = "0.2"
log = "0.3"
rand = "0.3"
rpassword = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sodiumoxide = "0.0.15"

[dev-dependencies]
tempdir = "0.3"
tempfile = "2.1"

[features]
default = ["clipboard"]

[lib]
name = "pwm_lib"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true

[[bin]]
name = "pwm"
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false
