[package]
name = "pwm"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
backtrace = "0.2"
bdrck_params = { path = "/home/ajr/workshop/rust/bdrck/bdrck_params", version = "0.1" }
byteorder = "1.0"
rpassword = "0.3"
serde = "0.8"
serde_derive = "0.8"
sodiumoxide = "0.0.12"
