[package]
name = "pwm"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]

[dependencies]
bdrck_config = "0.1"
bdrck_log = "0.3"
bdrck_params = "0.3"
bincode = "1.0.0-alpha2"
byteorder = "1.0"
clipboard = { version = "0.1", optional = true }
data-encoding = "1.2"
error-chain = "0.9"
git2 = { version = "0.6", default-features = false, features = [] }
isatty = "0.1"
lazy_static = "0.2"
log = "0.3"
rpassword = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
# TODO: Switch to a published version once #152 / fc43d8c is included in a release.
sodiumoxide = { git = "https://github.com/dnaq/sodiumoxide.git" }

[dev-dependencies]
tempdir = "0.3"
tempfile = "2.1"

[features]
default = ["clipboard"]

[lib]
name = "pwm_lib"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true

[[bin]]
name = "pwm"
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false
