[package]
name = "pwm"
version = "2.0.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
license = "Apache-2.0"

[dependencies]
bdrck = "0.9"
bincode = "1.0"
byteorder = "1.2"
clipboard = { version = "0.4", optional = true }
data-encoding = "2.1"
failure = "0.1"
git2 = { version = "0.7", default-features = false, features = [] }
isatty = "0.1"
lazy_static = "1.0"
log = "0.4"
rand = "0.5"
rpassword = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sodiumoxide = "0.1"

[features]
default = ["clipboard"]

[lib]
name = "pwm_lib"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true

[[bin]]
name = "pwm"
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false
